--- #YAML:1.0
name:               FCGI-Daemon
version:            0.20111121
abstract:           Perl-aware Fast CGI daemon for use with nginx web server.
author:
    - Dmitry Smirnov <onlyjob@cpan.org>
license:            AGPLv3
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    FCGI:               0.71
    FCGI::ProcManager:  0.18
    Getopt::Std:        0
    IO::Select:         0
    Test::More:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
